---
- set_fact:
    this_release_path: "{{ releases_path }}/{{ lookup('pipe', 'date +%Y-%m-%d_%H:%M:%S') }}"

- debug:
    msg: "New release path {{ this_release_path }}"

- name: Create general directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ user_name }}"
    group: "{{ group_name }}"
  with_items:
    - "{{ path }}"
    - "{{ releases_path }}"
    - "{{ shared_path }}"
    - "{{ shared_path }}/tmp"
    - "{{ shared_path }}/log"
    - "{{ shared_path }}/config"
    - "{{ shared_path }}/vendor"
    - "{{ shared_path }}/vendor/bundle"

- name: Create new release dir
  file:
    path: "{{ this_release_path }}"
    state: directory
    owner: "{{ user_name }}"
    group: "{{ group_name }}"

- name: Download code
  git:
    repo: "{{ git_url }}"
    dest: "{{ this_release_path }}"
    version: "{{ git_branch }}"
    accept_hostkey: yes
  register: git
  become: no

- debug:
    msg: "Cloned repo to commit: {{ git.after }}"

- name: "Create {{ shared_path }}/config/database.yml"
  template:
    src: database.yml.j2
    dest: "{{ shared_config_path }}/database.yml"
    owner: "{{ user_name }}"
    group: "{{ group_name }}"
    mode: 0600
    backup: yes

- name: "Copy config/secrets.yml to {{ shared_path }}/config"
  copy: 
    src: "../../../../../config/secrets.yml"
    dest: "{{ shared_config_path }}/secrets.yml"
    owner: "{{ user_name }}"
    group: "{{ group_name }}"
    mode: 0600

- name: Delete release's shared files
  file:
    path: "{{ this_release_path }}/{{ item }}"
    state: absent
  with_items:
    - config/database.yml
    - config/secrets.yml
    - "config/puma.{{ rails_env }}.rb"
    - log
    - tmp
    - vendor/bundle

- name: Symlink shared files
  file:
    src: "{{ shared_path }}/{{ item }}"
    dest: "{{ this_release_path }}/{{ item }}"
    state: link
    force: yes
  with_items:
    - config/database.yml
    - config/secrets.yml
    - "config/puma.{{ rails_env }}.rb"
    - log
    - tmp
    - vendor/bundle

- name: Install gems
  command: /bin/bash -lc 'bundle install --deployment --without "development test"'
  args:
    chdir: "{{ this_release_path }}"

- name: Precompile assets
  command: /bin/bash -lc 'bundle exec rake assets:precompile'
  environment:
    RAILS_ENV: "{{ rails_env }}"
  args:
    chdir: "{{ this_release_path }}"

- name: "Create & migrate database"
  command: /bin/bash -lc 'bundle exec rake db:create db:migrate'
  environment:
    RAILS_ENV: "{{ rails_env }}"
  args:
    chdir: "{{ this_release_path }}"

- name: Symlink new release
  file:
    src: "{{ this_release_path }}"
    dest: "{{ app_path }}"
    state: link
    force: yes

- name: Restart webserver
  command: "{{ server_restart_command }}"
  become: true
