---
- name: Configure puma
  template:
    src: puma.rb.j2
    dest: "{{ puma_config_path }}"

# - name: Install puma
#   command: /bin/bash -l -c 'gem install puma --no-ri --no-rdoc'
#     chdir: "{{ app_path }}"
#   sudo: no

- name: Check if puma is installed
  shell: /bin/bash -l -c 'which puma' chdir={{ app_path }}
  become_user: "{{ ruby_user_name }}" # make stdin tty
  register: puma_gem_check_result
  changed_when: false # never

- name: Install puma
  command: /bin/bash -l -c 'gem install puma --no-ri --no-rdoc' chdir={{ app_path }}
  become: false
  when: puma_gem_check_result.rc != 0

- name: Create directories for sockets and pids
  file:
    path: "{{ app_temp_path }}/{{ item }}"
    state: "directory"
  with_items:
    - pids
    - sockets
  become: false

- name: Create upstart config
  template:
    src: "upstart.conf.j2"
    dest: "/etc/init/{{ puma_app_name }}.conf"
  notify: restart application
