---
  - name: Allow ssh port through firewall
    ufw:
      direction: in
      port: ssh
      rule: allow
      proto: tcp
    become: true

  - name: Default to deny all incoming connections
    ufw:
      direction: in
      rule: deny
    become: true

  - name: Default to deny all outgoing connections
    ufw:
      direction: out
      rule: deny
    become: true

  - name: Enable firewall
    ufw:
      state: enabled
    become: true
