---
# ruby vars
ruby_install: rvm
ruby_version: 2.2.1
manual_ruby_version: 2.3.1
ruby_user_name: "{{ 'root' if ruby_install == 'package' else user_name }}"

# git vars
git_url: "git@bitbucket.org:amilgrom/{{ app_name }}.git"
git_branch: master

# directory structure vars
path: "/{{ app_name }}"
user_home_path: "/home/{{ user_name }}"

keep_releases: 5
releases_path: "{{ path }}/releases"
shared_path: "{{ path }}/shared"
environment_file: "{{ shared_path }}/.env"

app_path: "{{ path }}/current"
app_public_path: "{{ app_path }}/public"
app_config_path: "{{ app_path }}/config"
shared_config_path: "{{ app_path if target == 'virtualbox' else shared_path }}/config"
app_temp_path: "/tmp{{ app_path }}"
app_logs_path: "{{ app_path }}/log"

# puma vars
puma_app_name: "{{ app_name }}"
puma_bind_path: "unix://{{ app_temp_path }}/sockets/puma.{{ rails_env }}.sock"
puma_config_path: "{{ app_config_path }}/puma.{{ rails_env }}.rb"
puma_pidfile_path: "{{ app_temp_path }}/pids/puma.{{ rails_env }}.pid"
puma_stderr_redirect_path: "{{ app_logs_path }}/puma.{{ rails_env }}.err.log"
puma_stdout_redirect_path: "{{ app_logs_path }}/puma.{{ rails_env }}.log"
