---
- name: Provide basic security on all servers
  hosts: all
  remote_user: root
  become: true
  roles:
    - secured_server

- name: Create swap files on hard disk servers
  hosts: hdds
  roles:
    - swap

- name: Setup app proxy on all servers if specified
  hosts: all
  gather_facts: no
  roles:
    - { role: apt_proxy, when: use_apt_proxy }
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
      become: true

- name: Setup database servers
  hosts: dbservers
  roles:
    - base
    - postgresql

- name: Setup application servers
  hosts: appservers
  roles:
    - base
    - vim
    - { role: ruby, tags: ruby }
    - application
    - puma

- name: Setup web servers
  hosts: webservers
  roles:
    - base
    - nginx
